### ISSUE TITLE
Select APIs - Research API Documentation

### ISSUE THREAD

**Issue by Kovaceva11** [Kovaceva11/CheapDate#13]
Select Restaurant & Movie Review APIs

- Yelp! or TripAdvisor or Other
- Fandango or NewYorkTimes or Other

Notify GROUP of which APIs were selected and a quick note about WHY those APIs were selected. (ex: Ease of Use, Accessibility, etc.).

**Comment by 14Kappaman** [comment]
See comments regarding API's researched.

**Comment by 14Kappaman** [comment]
FANDANGO requires signing up with an acccount. Seems to be accessible without challenges thus far. Nothing of interest from the API list that was posted in SLACK. -AC
Alternatives: To access data through the Tripadvisor API if needed, you can make calls in the format:
http://api.tripadvisor.com/api/partner/2.0/location/155507?key=

Foursqure is comparable to Yelp but will require a fee.

**Comment by 14Kappaman** [comment]
Yelp may be more than what we needed requiring a server. Accessibility to TripAdvisor may be better option. -AC
